################################################################################
# 02-plot_histology-specific_splicing_events.R
# 
# Plots UpsetR plots based on splicing events generated by the 
# 
# written by Ammar Naqvi

# usage: Rscript 02-plot_histology-specific_splicing_events.R
################################################################################

##libraries 
suppressPackageStartupMessages({
  library("ggplot2")
  library("UpSetR")
  library("grid")
  library("cowplot")
  library("viridis")
  library("vroom")
  library("tidyverse")
})

#Get `magrittr` pipe
`%>%` <- dplyr::`%>%`

##set up directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "histology-specific-splicing")
results_dir <- file.path(analysis_dir, "results")

plots_dir <- file.path(analysis_dir, "plots")
if(!dir.exists(plots_dir)){
  dir.create(plots_dir, recursive=TRUE)
}

## output files for final plots
upsetR_es_plot_file          <- file.path(analysis_dir, "plots", "upsetR_histology-specific.es.pdf")
upsetR_ei_plot_file          <- file.path(analysis_dir, "plots", "upsetR_histology-specific.ei.pdf")
upsetR_tiff_es_plot_file     <- file.path(analysis_dir, "plots", "upsetR_histology-specific.es.tiff")
upsetR_tiff_ei_plot_file     <- file.path(analysis_dir, "plots", "upsetR_histology-specific.ei.tiff")

splice_event_df = vroom(paste0(results_dir,"/","splicing_events.hist-labeled_list.thr2freq.txt"), delim="\t", trim_ws = TRUE, col_names = TRUE)

## select and create list for exon skipping only events
splice_event_df_ATRT <- splice_event_df %>% filter(histology=='ATRT', type=='skipping') 
splice_event_df_CPG <- splice_event_df %>% filter(histology=='CPG', type=='skipping') 
splice_event_df_GNG <- splice_event_df %>% filter(histology=='GNG', type=='skipping') 
splice_event_df_EPN <- splice_event_df %>% filter(histology=='EPN', type=='skipping') 
splice_event_df_HGG <- splice_event_df %>% filter(histology=='HGG', type=='skipping') 
splice_event_df_MB <- splice_event_df %>% filter(histology=='MB', type=='skipping') 
splice_event_df_LGG <- splice_event_df %>% filter(histology=='LGG', type=='skipping')

list_for_skipping_upsetR <- list("ATRT"=splice_event_df_ATRT$splicing_event,
                                  "CPG"=splice_event_df_CPG$splicing_event,
                                 "GNG"=splice_event_df_GNG$splicing_event,
                                 "EPN"=splice_event_df_EPN$splicing_event,
                                 "HGG"=splice_event_df_HGG$splicing_event,
                                 "MB"=splice_event_df_MB$splicing_event,
                                 "LGG"=splice_event_df_LGG$splicing_event)
                                 
                                 
es_events <- upset(fromList(list_for_skipping_upsetR), 
                   mainbar.y.label = "", sets=c("ATRT","CPG","GNG","EPN","HGG","MB","LGG"), sets.x.label = "Histology", order.by = "freq",
                   mb.ratio = c(0.5,0.50), text.scale = c(1.3, 1.3, 1.3, 1.3, 2, 1.4),point.size = 2, line.size = 1.5, nsets = 7)


# Save plot as PDF
pdf(upsetR_es_plot_file, width = 16, height = 8)
es_events
dev.off()

# Save plot tiff version
tiff(upsetR_tiff_es_plot_file, height = 1200, width = 3600, res = 300)
print(es_events)
dev.off()

## get splicing events unique to each histology
ATRT <- setdiff(splice_event_df_ATRT$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                        splice_event_df_GNG$splicing_event,
                                                                                        splice_event_df_EPN$splicing_event,
                                                                                        splice_event_df_HGG$splicing_event,
                                                                                        splice_event_df_MB$splicing_event,
                                                                                        splice_event_df_LGG$splicing_event) ) ) )

CPG <- setdiff(splice_event_df_CPG$splicing_event, ( unique(c( splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

GNG <- setdiff(splice_event_df_GNG$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

EPN <- setdiff(splice_event_df_EPN$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

HGG <- setdiff(splice_event_df_HGG$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

MB <- setdiff(splice_event_df_MB$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                    splice_event_df_ATRT$splicing_event,
                                                                                    splice_event_df_GNG$splicing_event,
                                                                                    splice_event_df_EPN$splicing_event,
                                                                                    splice_event_df_HGG$splicing_event,
                                                                                    splice_event_df_LGG$splicing_event) ) ) )

LGG <- setdiff(splice_event_df_LGG$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event) ) ) )

LGG <- as.data.frame(LGG) %>% mutate(gene=str_match(LGG, "(\\w+)\\:")[, 2]) %>% dplyr::rename("splice_id" = "LGG") %>% mutate(histology="LGG")
MB <- as.data.frame(MB) %>% mutate(gene=str_match(MB, "(\\w+)\\:")[, 2]) %>% dplyr::rename("splice_id" = "MB") %>% mutate(histology="MB") 
HGG <- as.data.frame(HGG) %>% mutate(gene=str_match(HGG, "(\\w+)\\:")[, 2]) %>% dplyr::rename("splice_id" = "HGG") %>% mutate(histology="HGG") 
EPN <- as.data.frame(EPN) %>% mutate(gene=str_match(EPN, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "EPN") %>% mutate(histology="EPN") 
GNG <- as.data.frame(GNG) %>% mutate(gene=str_match(GNG, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "GNG") %>% mutate(histology="GNG") 
CPG <- as.data.frame(CPG) %>% mutate(gene=str_match(CPG, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "CPG")%>% mutate(histology="CPG") 
ATRT <- as.data.frame(ATRT) %>% mutate(gene=str_match(ATRT, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "ATRT")%>% mutate(histology="ATRT") 

splicing_ESevents_uniq_combined <- rbind(ATRT,MB,CPG,EPN,GNG,HGG,LGG)
write.table(splicing_ESevents_uniq_combined, paste0(results_dir,"/","histology-specific_events.es.total.tsv"), sep="\t",row.names = F, quote=FALSE, col.names = TRUE)


## select and create list for exon inclusion only events
splice_event_df_ATRT <- splice_event_df %>% filter(histology=='ATRT', type=='inclusion')
splice_event_df_CPG <- splice_event_df %>% filter(histology=='CPG', type=='inclusion') 
splice_event_df_GNG <- splice_event_df %>% filter(histology=='GNG', type=='inclusion') 
splice_event_df_EPN <- splice_event_df %>% filter(histology=='EPN', type=='inclusion') 
splice_event_df_HGG <- splice_event_df %>% filter(histology=='HGG', type=='inclusion') 
splice_event_df_MB <- splice_event_df %>% filter(histology=='MB', type=='inclusion') 
splice_event_df_LGG <- splice_event_df %>% filter(histology=='LGG', type=='inclusion') 

list_for_inclusion_upsetR <- list("ATRT"=splice_event_df_ATRT$splicing_event,
                                 "CPG"=splice_event_df_CPG$splicing_event,
                                 "GNG"=splice_event_df_GNG$splicing_event,
                                 "EPN"=splice_event_df_EPN$splicing_event,
                                 "HGG"=splice_event_df_HGG$splicing_event,
                                 "MB"=splice_event_df_MB$splicing_event,
                                 "LGG"=splice_event_df_LGG$splicing_event)

## make upsetR plots
ei_events <- upset(fromList(list_for_inclusion_upsetR), 
                   mainbar.y.label = "", sets.x.label = "Histology", order.by = "freq",
                   mb.ratio = c(0.5,0.50), text.scale = c(1.3, 1.3, 1.3, 1.3, 2, 1.4),point.size = 3, line.size = 1.5, nsets = 7)

# Save plot as PDF
pdf(upsetR_ei_plot_file, width = 16, height = 8)
ei_events
dev.off()

# Save plot tiff version
tiff(upsetR_tiff_ei_plot_file, height = 1200, width = 3600, res = 300)
print(ei_events)
dev.off()

## get splicing events unique to each histology
ATRT <- setdiff(splice_event_df_ATRT$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                        splice_event_df_GNG$splicing_event,
                                                                                        splice_event_df_EPN$splicing_event,
                                                                                        splice_event_df_HGG$splicing_event,
                                                                                        splice_event_df_MB$splicing_event,
                                                                                        splice_event_df_LGG$splicing_event) ) ) )

CPG <- setdiff(splice_event_df_CPG$splicing_event, ( unique(c( splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

GNG <- setdiff(splice_event_df_GNG$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

EPN <- setdiff(splice_event_df_EPN$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

HGG <- setdiff(splice_event_df_HGG$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_MB$splicing_event,
                                                                                      splice_event_df_LGG$splicing_event) ) ) )

MB <- setdiff(splice_event_df_MB$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                    splice_event_df_ATRT$splicing_event,
                                                                                    splice_event_df_GNG$splicing_event,
                                                                                    splice_event_df_EPN$splicing_event,
                                                                                    splice_event_df_HGG$splicing_event,
                                                                                    splice_event_df_LGG$splicing_event) ) ) )

LGG <- setdiff(splice_event_df_LGG$splicing_event, ( unique(c( splice_event_df_CPG$splicing_event,
                                                                                      splice_event_df_ATRT$splicing_event,
                                                                                      splice_event_df_GNG$splicing_event,
                                                                                      splice_event_df_EPN$splicing_event,
                                                                                      splice_event_df_HGG$splicing_event,
                                                                                      splice_event_df_MB$splicing_event) ) ) ) 


LGG <- as.data.frame(LGG) %>% mutate(gene=str_match(LGG, "(\\w+)\\:")[, 2]) %>% dplyr::rename("splice_id" = "LGG") %>% mutate(histology="LGG")
MB <- as.data.frame(MB) %>% mutate(gene=str_match(MB, "(\\w+)\\:")[, 2]) %>% dplyr::rename("splice_id" = "MB") %>% mutate(histology="MB") 
HGG <- as.data.frame(HGG) %>% mutate(gene=str_match(HGG, "(\\w+)\\:")[, 2]) %>% dplyr::rename("splice_id" = "HGG") %>% mutate(histology="HGG") 
EPN <- as.data.frame(EPN) %>% mutate(gene=str_match(EPN, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "EPN") %>% mutate(histology="EPN") 
GNG <- as.data.frame(GNG) %>% mutate(gene=str_match(GNG, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "GNG") %>% mutate(histology="GNG") 
CPG <- as.data.frame(CPG) %>% mutate(gene=str_match(CPG, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "CPG")%>% mutate(histology="CPG") 
ATRT <- as.data.frame(ATRT) %>% mutate(gene=str_match(ATRT, "(\\w+)\\:")[, 2])%>% dplyr::rename("splice_id" = "ATRT")%>% mutate(histology="ATRT") 

splicing_EIevents_uniq_combined <- rbind(ATRT,MB,CPG,EPN,GNG,HGG,LGG)
write.table(splicing_EIevents_uniq_combined, paste0(results_dir,"/","histology-specific_events.en.total.tsv"), sep="\t",row.names = F, quote=FALSE, col.names = TRUE)

