################################################################################
# 02-plot_histology-specific_splicing_events.R
# 
# Plots UpsetR plots based on splicing events generated by the 
# 
# written by Ammar Naqvi
#
# usage: Rscript 02-plot_histology-specific_splicing_events.R
################################################################################

## libraries 
suppressPackageStartupMessages({
  library("ggplot2")
  library("UpSetR")
  library("vroom")
  library("tidyverse")
})

#Get `magrittr` pipe
`%>%` <- dplyr::`%>%`

##set up directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "histology-specific-splicing")
results_dir <- file.path(analysis_dir, "results")

plots_dir <- file.path(analysis_dir, "plots")
if(!dir.exists(plots_dir)){
  dir.create(plots_dir, recursive=TRUE)
}

## output files for final plots
upsetR_es_plot_file          <- file.path(analysis_dir, "plots", "upsetR_histology-specific.es.pdf")
upsetR_ei_plot_file          <- file.path(analysis_dir, "plots", "upsetR_histology-specific.ei.pdf")

# Load the data using vroom
splice_event_df <- vroom::vroom(paste0(results_dir, "/", "splicing_events.hist-labeled_list.thr2freq.txt"), delim = "\t", trim_ws = TRUE, col_names = TRUE)

## make list out of all skipping events
list_for_skipping_upsetR <- splice_event_df %>%
  filter(type == 'skipping') %>%
  select(histology, splicing_event) %>%
  group_by(histology) %>%
  summarise(splicing_events = list(splicing_event)) %>% # Summarize as a list
  ungroup() %>%
  deframe()

# Generate the UpSetR plot
es_events <- upset(fromList(list_for_skipping_upsetR), order.by = "freq",keep.order = TRUE, mainbar.y.label = "", sets.x.label = "Histology",
                   mb.ratio = c(0.6,0.4), text.scale = c(5, 1.9, 1.5, 1.9, 2, 1.4),point.size = 2, line.size = 1, nsets = 17)

# Save plot
pdf(upsetR_es_plot_file, height = 10, width = 20)
print(es_events)
dev.off()

## make list out of all inclusion events
list_for_inclusion_upsetR <- splice_event_df %>%
  filter(type == 'inclusion') %>%
  select(histology, splicing_event) %>%
  group_by(histology) %>%
  summarise(splicing_events = list(splicing_event)) %>% # Summarize as a list
  ungroup() %>%
  deframe()

# Generate the UpSetR plot
ei_events <- upset(fromList(list_for_inclusion_upsetR), order.by = "freq",keep.order = TRUE, mainbar.y.label = "", sets.x.label = "Histology",
                   mb.ratio = c(0.6,0.4), text.scale = c(5, 1.9, 1.5, 1.9, 2, 1.4),point.size = 2, line.size = 1, nsets = 17)

# Save plot
pdf(upsetR_ei_plot_file, height = 10, width = 20)
print(ei_events)
dev.off()

## delete Rplots
unlink(file.path("Rplots.pdf"))