################################################################################
# 03-plot-histology-specific-norm-events.R
# 
# Plots UpsetR plots based on splicing events generated by the 
# 
# written by Ammar S. Naqvi, Ryan J. Corbett, Jo Lynne Rokita
#
# usage: Rscript 03-plot-histology-specific-norm-events.R
################################################################################

## libraries 
suppressPackageStartupMessages({
  library("ggplot2")
  library("UpSetR")
  library("vroom")
  library("tidyverse")
})

#Get `magrittr` pipe
`%>%` <- dplyr::`%>%`

##set up directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "histology-specific-splicing")
results_dir <- file.path(analysis_dir, "results")
cohort_sum_dir <- file.path(root_dir, "analyses", "cohort_summary")

plots_dir <- file.path(analysis_dir, "plots")
if(!dir.exists(plots_dir)){
  dir.create(plots_dir, recursive=TRUE)
}

## theme for all plots
figures_dir <- file.path(root_dir, "figures")
source(file.path(figures_dir, "theme_for_plots.R"))

# input file for colors
palette_file <- file.path(cohort_sum_dir, "results", "histologies-plot-group.tsv")
es_event_file <- file.path(results_dir, "unique_events-es.tsv")
ei_event_file <- file.path(results_dir, "unique_events-ei.tsv")

histology_df <- vroom(palette_file)
es_events <- vroom(es_event_file) %>% 
  rename(plot_group=Histology) %>%
  count(plot_group) %>%
  rename(unique_hits = n)

ei_events <- vroom(ei_event_file) %>% 
  rename(plot_group=Histology) %>%
  count(plot_group) %>%
  rename(unique_hits = n)

## filter using independent specimens file
independent_specimens_df <- read_tsv(file.path(data_dir,"independent-specimens.rnaseqpanel.primary.tsv")) %>%
  filter(cohort == "PBTA",
         experimental_strategy == "RNA-Seq")

# Merge both meta datasets
hist_indep_df <- histology_df %>%
  right_join(independent_specimens_df, by="Kids_First_Biospecimen_ID") %>% 
  unique() %>%
  filter(!is.na(plot_group)) %>%  # Remove rows with NA in plot_group
  count(plot_group) %>%
  rename(Total = n)

avg_unique_es_histology <-inner_join(es_events, hist_indep_df, by='plot_group') %>%
  mutate(norm_unique = unique_hits / Total)

avg_unique_ei_histology <-inner_join(ei_events, hist_indep_df, by='plot_group') %>%
  mutate(norm_unique = unique_hits / Total)

# Combine the two data frames with an additional column
combined_df <- bind_rows(
  avg_unique_es_histology %>% mutate(Preference = "Skipping"),
  avg_unique_ei_histology %>% mutate(Preference = "Inclusion")
)
#combined_df$Preference <- factor(combined_df$Preference, levels = c("Skipping", "Inclusion"))

# Sort the data frame in descending order by avg_unique of Skipping events
group_order <- combined_df %>%
  group_by(plot_group) %>%
  summarise(norm_unique_total = sum(norm_unique)) %>%
  arrange(norm_unique_total) %>%
  pull(plot_group)


# Create the side-by-side bar plot with custom colors
avg_uniq_plot <- ggplot(combined_df, aes(x = fct_relevel(plot_group, group_order), y = norm_unique, fill = Preference)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  scale_fill_manual(name = "Preference", values = c(Skipping = "#0C7BDC", Inclusion = "#FFC20A"))+ 
  labs(x = "Histology",
       y = "Unique Recurrent\nSplice Events per Patient") +
  theme_Publication() + 
  ylim(c(0,max(combined_df$norm_unique)+2))+
  coord_flip()+
  theme(legend.position = "top",
        legend.direction = "horizontal")
  
# Save plot
pdf(file.path(plots_dir,"avg-uniq-hits.pdf"), height = 7, width = 7)
print(avg_uniq_plot)
dev.off()

