---
title: "polyA vs stranded assessment"
author: "Ammar S Naqvi"
date: "2024-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
# Load required libraries
library(tidyverse)
library(vroom)
library(data.table)
library(ggpubr)
```

Directory set up and process input data

```{r }
# Define directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "stranded-polyA-assessment")
plots_dir <- file.path(analysis_dir, "plots")
figures_dir <- file.path(root_dir, "figures")
```

```{r}
# Specify file paths
clin_file  <- file.path(data_dir,"histologies.tsv")
rmats_file <- file.path(data_dir, "splice-events-rmats.tsv.gz")

# Read data
clin_df <- vroom(clin_file, show_col_types = FALSE) %>% 
  filter(experimental_strategy=='RNA-Seq')

rmats_df <- fread(rmats_file)

# Load custom theme for plots
source(file.path(figures_dir, "theme_for_plots.R"))

```

Generate polyA vs stranded plots on known samples: PT_RYMG3M91 and PT_W5GP3F6B

```{r}
# General plots assessing PSI in poly A vs Str for known samples PT_RYMG3M91 and PT_W5GP3F6B
clin_to_check_df <- clin_df %>% 
  filter(Kids_First_Participant_ID %in% c('PT_RYMG3M91', 'PT_W5GP3F6B'))

# Select two sample_ids for comparison
polya_id <- "BS_68KX6A42"
stranded_id <- "BS_D7XRFE0R"

# Filter data for selected sample IDs
psi_PT_RYMG3M91 <- rmats_df %>% 
  filter(sample_id %in% c(polya_id, stranded_id)) %>% 
  filter(splicing_case=='SE') %>%
  dplyr::mutate(SpliceID = paste(geneSymbol, exonStart_0base, exonEnd, upstreamES,upstreamEE,downstreamES,downstreamEE, sep = ":")) %>%
  select(sample_id,SpliceID,IncLevel1)

# Filter data for the selected sample_ids
sample1_data <- psi_PT_RYMG3M91 %>%
  filter(sample_id == polya_id)
sample2_data <- psi_PT_RYMG3M91 %>%
  filter(sample_id == stranded_id)

# Merge data for the same SpliceID
merged_data <- merge(sample1_data, sample2_data, by = "SpliceID", suffixes = c("_polya", "_stranded"))

# Create scatterplot using ggscatter
PT_RYMG3M91_scatter <- ggscatter(merged_data, x = "IncLevel1_polya", y = "IncLevel1_stranded", 
               xlab = paste(polya_id, "PSI (poly-A)"),
               ylab = paste(stranded_id, "PSI (stranded)"),
               add = "reg.line", 
               conf.int = TRUE, 
               cor.coef = TRUE, 
               cor.method = "pearson",
               add.params = list(color = "red", fill = "pink"),
               ticks = TRUE) + 
               theme_Publication()

# Print and save plot as pdf
print(PT_RYMG3M91_scatter)
```

```{r}
# Select two sample_ids for comparison from PT_W5GP3F6B
polya_id2 <- "BS_7WM3MNZ0"
stranded_id2 <- "BS_KABQQA0T"

# Filter data for the selected sample_ids
psi_PT_W5GP3F6B <- rmats_df %>% 
  filter(sample_id %in% c(polya_id2, stranded_id2)) %>% 
  filter(splicing_case=='SE') %>%
  dplyr::mutate(SpliceID = paste(geneSymbol, exonStart_0base, exonEnd, upstreamES,upstreamEE,downstreamES,downstreamEE, sep = ":") ) %>%
  select(sample_id,SpliceID,IncLevel1)

# Filter data for the selected sample_ids
sample1_data <- psi_PT_W5GP3F6B %>%
  filter(sample_id == polya_id2)
sample2_data <- psi_PT_W5GP3F6B %>%
  filter(sample_id == stranded_id2)

# Merge data for the same SpliceID
merged_data <- merge(sample1_data, sample2_data, by = "SpliceID", suffixes = c("_polya", "_stranded"))

# Create scatterplot using ggscatter
PT_W5GP3F6B_scatter <- ggscatter(merged_data, x = "IncLevel1_polya", y = "IncLevel1_stranded", 
               xlab = paste(polya_id2, "PSI (poly-A)"),
               ylab = paste(stranded_id2, "PSI (stranded)"),
               add = "reg.line", 
               conf.int = TRUE, 
               cor.coef = TRUE, 
               cor.method = "pearson",
               add.params = list(color = "red", fill = "pink", alpha = 0.05),
               ticks = TRUE) + 
               theme_Publication()

# Print and save plot as pdf
print(PT_W5GP3F6B_scatter)
```

