---
title: "Pan cancer analysis"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

Load required libraries
```{r}
library("limma")
library("gplots")
library("ConsensusClusterPlus")

# Get `magrittr` pipe
`%>%` <- dplyr::`%>%`
```
Publication theme for plots
```{r}
##theme for all plots
theme_Publication <- function(base_size=15, base_family="Helvetica") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            panel.border = element_rect(colour = NA),
            axis.title = element_text(face = "bold",size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(), 
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_line(colour="#f0f0f0"),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "right",
            legend.direction = "vertical",
            legend.key.size= unit(0.5, "cm"),
            # legend.margin = unit(0.5, "cm"),
            legend.margin = margin(5,5,5,5),
            legend.title = element_text(face="bold"),
            #plot.margin=unit(c(10,5,5,5),"mm"),
            plot.margin=unit(c(10,5,5,10),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold")
    ))
}

```

Import files and tables (subset of 30 samples/histology)
PCA plot
```{r}
## filter for inclusion threshold 10, PSI, 80% prev per hist type
file= "/Users/naqvia/Desktop/pan_cancer_rmats/test_matrix.thr10hist30histprev2.psi.tsv"
psi_tab <- read.table(file, row.names = 1, sep = "\t",header = TRUE)


## capture par settings, then add space to the right
opar <- par(no.readonly = TRUE)
par(xpd = TRUE, mar = par()$mar + c(0, 0, 0, 5))

x=plotMDS(log(psi_tab), xlab = "PC1", ylab="PC2", cex.lab= 1, cex = 1, col = c( c(rep("blue", 30)),c(rep("purple",30)), c(rep("black",1 )),c(rep("black",1)), c(rep("violet",30)), c(rep("grey",30)),c(rep("darkred",30)), c(rep("red",30)), c(rep("darkgreen",30)),c(rep("grey",2))), pch=16)
legend(par("usr")[2], par("usr")[4], c("ATRT","Cran","EWS","Embr","Epend","Gangl", "HGAT", "LGAT", "Medullo", "Olig"),col = c("blue","purple","black","black","violet","grey","darkred","red","darkgreen","grey"), pch = 16, bty = "n")


```


Consensus clustering
```{r}
rnames <- psi_tab[,1]
row.names(psi_tab) <- psi_tab$Splice_ID
mat_hm <- data.matrix(psi_tab[,2:ncol(psi_tab)])

d=mat_hm
# d[1:5,1:5]

## reduce the dataset to the top 5,000 most variable genes, measured by median absolute deviation
mads=apply(d,1,mad)
d=d[rev(order(mads))[1:5000],]

## the default settings of the agglomerative hierarchical clustering algorithm using Pearson correlation distance, so it is appropriate to gene median center d using
d = sweep(d,1, apply(d,1,median,na.rm=T))


## remove NAs
is.na(d) <- sapply(d, is.infinite)
d[is.na(d)] <- 0
d[is.nan(d)] <- 0

## Run ConsensusClusterPlus
title="/Users/naqvia/Desktop/pan_cancer_rmats"
results= ConsensusClusterPlus((d),maxK=10,reps=100,pItem=0.8,
                    title="PSI Clustering",clusterAlg="hc",distance="spearman",seed=123,innerLinkage = "average", finalLinkage = "average", plot="png")

ConsensusClusterPlus((d),maxK=10,reps=100,pItem=0.8,
                     title="clustering",clusterAlg="hc",distance="spearman",seed=123,innerLinkage = "average", finalLinkage = "average")

## do all of the samples // pan_cancer_splicing.thr10.report_all.txt
file = "/Users/naqvia//Desktop/AS-DMG/data/pan_cancer_splicing.thr10.report_all.txt"
psi_tab <- read.delim(file, row.names = 1,sep = "\t", header = TRUE)

rnames <- psi_tab[,1]
row.names(psi_tab) <- psi_tab$Splice_ID
mat_hm <- data.matrix(psi_tab[,2:ncol(psi_tab)])

d=mat_hm

## reduce the dataset to the top 1,000 most variable genes, measured by median absolute deviation
mads=apply(d,1,mad)
d=d[rev(order(mads))[1:1000],]

## the default settings of the agglomerative hierarchical clustering algorithm using Pearson correlation distance, so it is appropriate to gene median center d using
d = sweep(d,1, apply(d,1,median,na.rm=T))


## remove NAs
is.na(d) <- sapply(d, is.infinite)



d[is.na(d)] <- 0
d[is.nan(d)] <- 0

## k= 7 
#ConsensusClusterPlus((d),maxK=7,reps=100,pItem=0.8,
#                     title="clustering",clusterAlg="hc",distance="spearman",seed=123,innerLinkage = "average", finalLinkage = "average")

##save to file
#title="/Users/naqvia/Desktop/pan_cancer_rmats"
#results= ConsensusClusterPlus((d),maxK=7,reps=100,pItem=0.8,
#                     title="Total Samples PSI Clustering",clusterAlg="hc",distance="spearman",seed=123,innerLinkage = "average", finalLinkage = "average", plot="png")

##save to variable in order to be used below, k=6
results = ConsensusClusterPlus((d),maxK=10,reps=100,pItem=0.8,
                     title="clustering",clusterAlg="hc",distance="spearman",seed=123,innerLinkage = "average", finalLinkage = "average")

```
Heatmap version so you can print labels with histologies 
```{r}
library("pheatmap")

# choose a cluster that seems best and assign to n_cluster
CC_group <- results[[6]]$consensusClass %>%
  as.data.frame()
colnames(CC_group) <- "CC"

# read in consensus clustering matrix
CC_consensus_mat <- results[[6]]$consensusMatrix
colnames(CC_consensus_mat) <- rownames(CC_group)
rownames(CC_consensus_mat) <- rownames(CC_group)


clin_file = "~/Desktop/AS-DMG/data/pbta-histologies.RNA-Seq.tsv"
clin_tab = read.delim(clin_file, sep = "\t", header=TRUE)

clin_file = "~/Downloads/compiled_molecular_subtypes_with_clinical_pathology_feedback.tsv"
clin_tab = read.delim(clin_file, sep = "\t", header=TRUE)

hist_sample <- cbind(data.frame(clin_tab$Kids_First_Biospecimen_ID), data.frame(clin_tab$short_histology), data.frame(clin_tab$integrated_diagnosis), data.frame(clin_tab$tumor_descriptor))
library(randomcoloR)

## n is total num of histology (short)
anno_palette <- distinctColorPalette(10)

names(anno_palette)<- unique(clin_tab$short_histology)

hist_sample$clin_tab.short_histology <- as.factor(hist_sample$clin_tab.short_histology )



names(anno_palette)<- levels(hist_sample$clin_tab.short_histology)
rownames(hist_sample)<- hist_sample$clin_tab.Kids_First_Biospecimen_ID

##remove colum
hist_sample = subset(hist_sample, select = -c(clin_tab.Kids_First_Biospecimen_ID))

pheatmap::pheatmap(
  CC_consensus_mat,
  #color = colorRampPalette(brewer.pal(n = 9, name = "Blues"))(9),
  annotation_col=hist_sample, 
  #annotation_colors=anno_palette,
  cluster_rows = results[[6]]$consensusTree,
  cluster_cols = results[[6]]$consensusTree, 
  show_rownames = F,
  show_colnames = F
  #filename = "cc_test/png",
  #fontsize = 10, cellwidth = 10, cellheight = 10
)

## save cluster members
CC_group <- results[[6]]$consensusClass %>%
    as.data.frame()

```

##Splicing index plot
```{r}
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)

file = "/Users/naqvia/Desktop/AS-DMG/analyses/pan_cancer/results/splicing_index.wdPSI.txt"
splice_index = read.table(file,header=TRUE, row.names=1, sep = "\t")

## more accurate version
file = "/Users/naqvia/Desktop/AS-DMG/analyses/pan_cancer/results/splicing_index.wdPSI_per_sample.txt"
splice_index = read.table(file,header=TRUE, row.names=1, sep = "\t")


e <- ggplot(splice_index, aes(x = hist, y = splice_index))


e + geom_violin(trim = FALSE) + 
  stat_summary(
    fun.data = "mean_sdl",  fun.args = list(mult = 1), 
    geom = "pointrange", color = "black"
  )

e + geom_violin(aes(fill = hist), trim = FALSE) + 
  geom_boxplot(width = 0.2) +
  #scale_fill_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
  geom_point(color="black", size=1, position = position_jitter(w=0.02)) +
  theme(legend.position = "none") + theme_Publication()

```

## Make CDF plot for splicing index
```{r}
splice_index <- splice_index %>%
    as.data.frame(stringsAsFactors = FALSE)

 
# Set up the data.frame for plotting
  si_cdf <- splice_index %>%
    # We only really need these two variables from data.frame
    dplyr::transmute(
      group = hist,
      number = as.numeric(splice_index)
    ) %>%
    # Group by specified column
    dplyr::group_by(group) %>%
    # Only keep groups with the specified minimum number of samples
    dplyr::filter(dplyr::n() > 1) %>%
    # Calculate group median
    dplyr::mutate(
      group_median = median(number, na.rm = TRUE),
      group_rank = rank(number, ties.method = "first") / dplyr::n(),
      sample_size = paste0("n = ", dplyr::n())
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(group = reorder(group, group_median))

  # Set y_lim as min and max if it was not set
  #if (is.na(y_lim)) {
   # y_lim = c(min(df$number),
   #           max(df$number))
  #}
  
  
si_cdf %>%
    # Now we will plot these as cumulative distribution plots
    ggplot2::ggplot(ggplot2::aes(
      x = group_rank,
      y = number
    )) +
  
    ggplot2::geom_point(color = "black") +
  
    # Add summary line for median
    ggplot2::geom_segment(
      x = 0, xend = 1, color = "blue",
      ggplot2::aes(y = group_median, yend = group_median)
    ) +
  
    # Separate by histology
    ggplot2::facet_wrap(~ group + sample_size, nrow = 1, strip.position = "bottom") +
    ggplot2::theme_classic() +
    ggplot2::xlab("Histology") +
    ggplot2::ylab("Splicing Index") +
  
   # # Transform to log10 make non-log y-axis labels
   # ggplot2::scale_y_continuous(
   #   trans = "-log",
   #    limits = 1,
   #    breaks = as.numeric(breaks)
   #  ) +
  
    #ggplot2::scale_x_continuous(limits = 2) +
  
    # Making it pretty
    ggplot2::theme(legend.position = "none") +
    ggplot2::theme(
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      strip.placement = "outside",
      strip.text = ggplot2::element_text(size = 10, angle = 90, hjust = 1),
      strip.background = ggplot2::element_rect(fill = NA, color = NA)
    ) +
    ggplot2::ggtitle("Splicing Index")


```

